# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170525_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='priority',
            field=models.IntegerField(help_text='Lower number comes first in menu'),
        ),
    ]
