# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170525_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['priority'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
