# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170525_0458'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
