# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170525_0544'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
            ],
        ),
    ]
