# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 07:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170525_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('permanent_address', ckeditor.fields.RichTextField()),
                ('mailing_address', ckeditor.fields.RichTextField()),
                ('degree_1', models.CharField(max_length=100)),
                ('major_1', models.CharField(max_length=100)),
                ('institution_1', models.CharField(max_length=100)),
                ('year_1', models.CharField(max_length=4)),
                ('degree_2', models.CharField(blank=True, max_length=100, null=True)),
                ('major_2', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_2', models.CharField(blank=True, max_length=100, null=True)),
                ('year_2', models.CharField(blank=True, max_length=4, null=True)),
                ('degree_3', models.CharField(blank=True, max_length=100, null=True)),
                ('major_3', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_3', models.CharField(blank=True, max_length=100, null=True)),
                ('year_3', models.CharField(blank=True, max_length=4, null=True)),
                ('degree_4', models.CharField(blank=True, max_length=100, null=True)),
                ('major_4', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_4', models.CharField(blank=True, max_length=100, null=True)),
                ('year_4', models.CharField(blank=True, max_length=4, null=True)),
                ('from_1', models.DateField()),
                ('to_1', models.DateField()),
                ('organization_1', models.CharField(max_length=255)),
                ('description_of_work_1', ckeditor.fields.RichTextField()),
                ('from_2', models.DateField(blank=True, null=True)),
                ('to_2', models.DateField(blank=True, null=True)),
                ('organization_2', models.CharField(blank=True, max_length=255, null=True)),
                ('description_of_work_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('from_3', models.DateField(blank=True, null=True)),
                ('to_3', models.DateField(blank=True, null=True)),
                ('organization_3', models.CharField(blank=True, max_length=255, null=True)),
                ('description_of_work_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('from_4', models.DateField(blank=True, null=True)),
                ('to_4', models.DateField(blank=True, null=True)),
                ('organization_4', models.CharField(blank=True, max_length=255, null=True)),
                ('description_of_work_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('from_5', models.DateField(blank=True, null=True)),
                ('to_5', models.DateField(blank=True, null=True)),
                ('organization_5', models.CharField(blank=True, max_length=255, null=True)),
                ('description_of_work_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('membership_of_any_other', models.CharField(blank=True, max_length=255, null=True)),
                ('present_position', models.CharField(blank=True, max_length=255, null=True)),
                ('employeer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('recommenders_name', models.CharField(blank=True, max_length=255, null=True)),
                ('membership_no', models.IntegerField(blank=True, default=0, null=True)),
                ('membership_status', models.CharField(blank=True, max_length=255, null=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
