# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 09:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170525_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='office_address',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='employeer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
