# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170527_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 8, 22, 3, 898384, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
